### ISSUE TITLE
Support russian language?!?

### ISSUE THREAD

**Issue by jhnf** [miblooming/JZ-TS24-2#1]
Hi, great display! I'd like to see the Russian language on your display, is it possible ?. Anyway, I can help with the translation.

**Comment by jhnf** [comment]
Hello!
I figured out how to translate the ui_editor, but the font is ugly for the Russian language. It would be nice to change the font to another one, like Cambria.

**Comment by miblooming** [comment]
Yes, I have send you email.

**Comment by jhnf** [comment]
Thanks!

**Comment by Muhin555** [comment]
I do not know the Chinese language. So I can't buy a display Taobao. There is a possibility to buy it on AliExpress? A lot of my friends in Russia would like to buy it.

**Comment by miblooming** [comment]
Yes, I'll upload this product to AliExpress these days. Then send  the URL link to you.

**Comment by miblooming** [comment]
@Muhin555  Paypal is ok for order. Upload product to AliExpress it too expensive. Email to me for detail, thank you. My email is loomingxu@qq.com

**Comment by Muhin555** [comment]
I'm send letter to email loomingxu@qq.com

**Comment by miblooming** [comment]
@Muhin555 Your email is classified as a spam email, but I find it now. And i have reply your email.

**Comment by Muhin555** [comment]
Ок. I'm read your email.

**Comment by miblooming** [comment]
Russian is supported now.
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5)
