### ISSUE TITLE
No Wifi after Update

### ISSUE THREAD

**Issue by TAOGde** [miblooming/JZ-TS24-2#12]
after update my Flyingbear-Ghost4 display I got the new firmware on the display but the wifi card does not work.
the update process for the wifi hangs at 0% and I got an error when I try to access the wifi button that no card has found.

lates Flyingbear-Ghost4 with green touchscreen board. (v1.4)

**Comment by miblooming** [comment]
Flyingbear-Ghost4 is a customization version of JZ-TS.It's wifi module not the same as JZ-TS. Upgrade the original  firmwave of  Ghost4 can solve your problem.
