### ISSUE TITLE
Cura plugin

### ISSUE THREAD

**Issue by TAOGde** [miblooming/JZ-TS24-2#13]
I try your plugin with Cura latest version and your plugin for Flyingbear-Ghost4 latest version.
cura crashed on click to open the UI.
<img width="2560" alt="Bildschirmfoto 2019-06-19 um 18 27 56" src="https://user-images.githubusercontent.com/43980652/59784327-7114a580-92c2-11e9-8dd8-3c6cf225120c.png">

[error report.txt](https://github.com/miblooming/JZ-TS24-2/files/3307108/error.report.txt)
[protokoll.txt](https://github.com/miblooming/JZ-TS24-2/files/3307109/protokoll.txt)

**Comment by miblooming** [comment]
Please download the new version here:
FlyingBearIntegration.zip
https://github.com/miblooming/JZ-TS24-2/tree/master/other/FlyingBear_TS_WIFI
