### ISSUE TITLE
control signal to a outside camera per layer ?

### ISSUE THREAD

**Issue by fred2088** [miblooming/JZ-TS24-2#14]
is there any control signal from 2.4"/2.8"/3.5"/4" during each layer change to toggle a camera snapshot connected to it ?

**Comment by miblooming** [comment]
In theory, I can add a Event Trigger of layer for this purpose.

**Comment by fred2088** [comment]
yes, please

**Comment by miblooming** [comment]
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)
![layer_change_event](https://user-images.githubusercontent.com/2108904/61650780-030b3600-ace7-11e9-9225-80cc11e1649e.png)

**Comment by fred2088** [comment]
how about TS24 ?
