### ISSUE TITLE
TS24 without hotbed ?

### ISSUE THREAD

**Issue by fred2088** [miblooming/JZ-TS24-2#15]
the hotbed block is deleted from the printing status screen due to the machine isn't have hotbed,
but it's still showing 0/0 from orginal place evening deleted ?

current fix is to move those field to outside of the screen ?
is it possible not to display those info if the machine is defined don't have hotbed ?

Regards

**Comment by miblooming** [comment]
Yes, move those field to outside of the screen at the moment.
And i'll add an option to hide those later.

**Comment by fred2088** [comment]
thanks a lot
