### ISSUE TITLE
JZ-TS35WIFI__(3.5)_portrait mode

### ISSUE THREAD

**Issue by edsant1812** [miblooming/JZ-TS24-2#17]
I'm launching a new line of 3D printers in my country and I'm using the JZ-TS35WIFI__(3.5) diaplays. I wonder if it would be possible to use them in portrait mode, similar to the JZ-TS24

**Comment by miblooming** [comment]
Yes. Please give me some infoamtion of your company.
We can make a portrait theme for you.

**Comment by edsant1812** [comment]
perfect, what information is needed and in which email I can pass this information

**Comment by miblooming** [comment]
My email is loomingxu@qq.com.
Can you send us the introduction of you company and product.

**Comment by miblooming** [comment]
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/firmwave%20lastest_portrait
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/UIEditor__portrait
![protrait_theme](https://user-images.githubusercontent.com/2108904/61650671-cdfee380-ace6-11e9-8462-f3aeffe62801.png)
