### ISSUE TITLE
New menue for IDEX or DUAL_X_CARRIAGE Printer

### ISSUE THREAD

**Issue by RV3Dtech** [miblooming/JZ-TS24-2#18]
Can you create an Menue for IDEX Printers? Marlin call: DUAL_X_CARRIAGE
http://marlinfw.org/docs/gcode/M605.html

Menue like Pictures from standard LCD 

It should also shows the different IDEX modes.

That would be a unique point for this display, nobody else has. 

![PicsArt_08-11-03 54 55](https://user-images.githubusercontent.com/50876608/62834956-4526f800-bc53-11e9-8bed-6dbaf9736319.jpg)
![IMG_20190811_144405968~2](https://user-images.githubusercontent.com/50876608/62834962-5bcd4f00-bc53-11e9-98c7-db25505c4314.jpg)
![IMG_20190811_144503452~2](https://user-images.githubusercontent.com/50876608/62834963-5bcd4f00-bc53-11e9-9485-998c4340f9a1.jpg)

**Comment by miblooming** [comment]
I'll try it.

**Comment by miblooming** [comment]
Please check out the new version of V3.8.2
IDEX menu added.
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)
