### ISSUE TITLE
ATX power supply and encoder

### ISSUE THREAD

**Issue by jhnf** [miblooming/JZ-TS24-2#2]
Hello!
How to connect the screen to control the ATX power supply?
In the editor there is a mention of the encoder, how can it be connected?

**Comment by miblooming** [comment]
1.Connect to ramps to enable Gcode M81
OR
2.Use a repay (LOW LEVEL TRIGGER WITH INPUT 3.3V)
https://github.com/miblooming/JZ-TS24-2/blob/master/%E6%9C%BA%E6%99%BA3D%E6%89%93%E5%8D%B0%E8%A7%A6%E6%8E%A7%E5%B1%8F%E8%B5%84%E6%96%99/%E8%87%AA%E5%8A%A8%E5%85%B3%E6%9C%BA%E6%A8%A1%E5%9D%97-%E7%BB%84%E8%A3%85%E8%AF%B4%E6%98%8E.pdf
