### ISSUE TITLE
JZ-TS40 BabbyStepping

### ISSUE THREAD

**Issue by ffnull** [miblooming/JZ-TS24-2#21]
Hello.Recently buy your display. Best controller ever. Wifi printing is awsome, but i need babbystepping to correct first layer. How i can add it or can you add it?

**Comment by ffnull** [comment]
Project abadoned? no support at all?

**Comment by miblooming** [comment]
Sorry, I am not  familiar with babbystepping. I am learning about this iusse.

**Comment by ffnull** [comment]
So? Any solution? http://marlinfw.org/docs/gcode/M290.html

**Comment by miblooming** [comment]
Three methods：
1.Add some codes in Gcode file by modifing the setting "Starting G-Code" of slicer software
2.Add a button on screen by UIEditor to trigger G290-operation  by handwork
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)
https://www.youtube.com/playlist?list=PLamn4I4Ptg5KcN8KiLsWBeAiS-ABRkXjR
3.Add an event operation of   by UIEditor 
![event_trigger20191006173618](https://user-images.githubusercontent.com/2108904/66267114-e307ff00-e85f-11e9-9224-ae3d6c0c4a2e.png)

**Comment by ffnull** [comment]
I need add it to main screen of printing process. Button must be near buttons of corrections of temperatures of heaters. on center of button must be shown real height of Z and it must be change while clicking up and down

**Comment by ffnull** [comment]
Here another example how its work https://youtu.be/s5kld8MIo6M

**Comment by miblooming** [comment]
Please try it on UIEditor.
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)
https://www.youtube.com/playlist?list=PLamn4I4Ptg5KcN8KiLsWBeAiS-ABRkXjR

**Comment by ffnull** [comment]
by the way. no sizes and no models for jz-ts40.

**Comment by miblooming** [comment]
The firmware of jz-ts40 is same as jz-ts35

**Comment by RV3Dtech** [comment]
![image](https://user-images.githubusercontent.com/50876608/68785632-c15c1d80-063e-11ea-8ca5-86b22449f81f.png)

![image](https://user-images.githubusercontent.com/50876608/68785686-d933a180-063e-11ea-9952-275747f164b6.png)

**Comment by miblooming** [comment]
> by the way. no sizes and no models for jz-ts40.
Here:
https://github.com/miblooming/JZ-TS24-2/blob/master/size_shell/JZ-TS40_4.0shellV1.0-solidworks2016.zip
