### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by tuzkov** [miblooming/JZ-TS24-2#25]
Hello!
Do you have some kind of documentation for screen API?
By Cura plugin I find some APIs, but I not sure that is all.
At least I want to switch screen to "offline" mode by WIFI to print via USB.
Thank you!

**Comment by miblooming** [comment]
There's no code to set offline. I can add some api and give you a document at next version. Maybe somedays later.


 
---Original---

**Comment by tuzkov** [comment]
Nice! Thank you!

**Comment by miblooming** [comment]
Please use the new firmware
V3.7.6
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/firmwave%20lastest_landscape

API file here:
https://github.com/miblooming/JZ-TS24-2/blob/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/API_for_wifi.txt

Send 7998 Disconnect
Send 7993 Reconnect

**Comment by Zorchz** [comment]
Is it possible to update flyingbear version with that change?
I'm about https://github.com/miblooming/JZ-TS24-2/tree/master/other/flyingbear/firmwave

**Comment by miblooming** [comment]
I'm sorry. The&nbsp;flyingbear version is a custom version. I'll not upgrade it privately.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zorchz"<notifications@github.com&gt;; 
发送时间: 2019年11月11日(星期一) 晚上7:04
收件人: "miblooming/JZ-TS24-2"<JZ-TS24-2@noreply.github.com&gt;; 
抄送: "looming"<loomingxu@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [miblooming/JZ-TS24-2] API documentation (#25)




Is it possible to update flyingbear version with that change?
 I'm about https://github.com/miblooming/JZ-TS24-2/tree/master/other/flyingbear/firmwave
 
&mdash;
