### ISSUE TITLE
Auto power off bug

### ISSUE THREAD

**Issue by lowv** [miblooming/JZ-TS24-2#26]
Hello,
first I want to commend you for your work. Best upgrade for my printer!
I habe an IDEX / dual extrusion machine with auto power-off enabled. There's an issue when I use T1 hotend and finish printing, it powers off immediately without cool down.
Also it would make sense to be able to switch between T0/T1 in the move menu, similar to preheat..

Thanks!

**Comment by miblooming** [comment]
Auto power off bug: It's bug, I'll fix it.

Switch Hotend:
Add tow buttons by UIEditor, send gcode: T0 or T1
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/UIEditor_landscape

At next upgrade, I'll add a button to switch hotend on move page.
