### ISSUE TITLE
Plugin [FlyingBearPlugin] with supported sdk versions [['6.0.0', '6.0.0']] is incompatible with the current sdk version [7.0.0].

### ISSUE THREAD

**Issue by TAOGde** [miblooming/JZ-TS24-2#27]
I got this error with latest CURA 4.4.1

WARNING - [MainThread] UM.PluginRegistry.loadPlugin [374]: Plugin [FlyingBearPlugin] with supported sdk versions [['6.0.0', '6.0.0']] is incompatible with the current sdk version [7.0.0].

**Comment by miblooming** [comment]
I'll update the plugin to use the newest SDK of cura! Thank your for your feedback.

**Comment by miblooming** [comment]
cura plugin for cura4.4
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/cura%20plugin
