### ISSUE TITLE
Please update russian translation.

### ISSUE THREAD

**Issue by Pilson66** [miblooming/JZ-TS24-2#32]
I am a native speaker of the russian language, and I tried to translate the entire interface as correctly as possible.
Please update the translation. The file with the translation is attached.
[jz-ts_russian_translation.xlsx](https://github.com/miblooming/JZ-TS24-2/files/4144640/jz-ts_russian_translation.xlsx)

Also, the program does not have the ability to change ID 2021. There need to change "Русский язык" to "Русский".
Thanks.

**Comment by miblooming** [comment]
Thank you!

**Comment by miblooming** [comment]
Please check it here.
New russian translation.
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)

**Comment by Pilson66** [comment]
Reviewed again in detail, and found a few more inaccuracies. Please update.
File is attached.
[jz-ts_russian_translation_update_1.xlsx](https://github.com/miblooming/JZ-TS24-2/files/4147672/jz-ts_russian_translation_update_1.xlsx)

**Comment by miblooming** [comment]
Done.
Please check it.

**Comment by Pilson66** [comment]
It looks quite presentable.
Thanks.

**Comment by Pilson66** [comment]
One more (maybe last) correction, please update.
[jz-ts_russian_translation_update_2.xlsx](https://github.com/miblooming/JZ-TS24-2/files/4148650/jz-ts_russian_translation_update_2.xlsx)

**Comment by miblooming** [comment]
It's done.

**Comment by Pilson66** [comment]
Please update one more translation.

ID|China|English|Russian
----|-----|-----|-----
1163	|	数值过大	|	Too large	|	Значение слишком большое

**Comment by miblooming** [comment]
OK. Next update.


 
---Original---

**Comment by Pilson66** [comment]
Hello. Any updates?

**Comment by miblooming** [comment]
1136 is done.
