### ISSUE TITLE
Wifi not work on 3.8.0fw

### ISSUE THREAD

**Issue by Yandex-an** [miblooming/JZ-TS24-2#34]
Hello, after updating the TS40 display(Flyingbear) to 3.8.0 fw, WIFI does not work. Wifi only works on Flyingbear FW. What can I do about it?

**Comment by Yandex-an** [comment]
Does WIFI work if I solder ESP32 to the board?

**Comment by miblooming** [comment]
No. Wire is&nbsp; different.

**Comment by Yandex-an** [comment]
Can you send me an ESP32 connection diagram to STM, for your display?

**Comment by miblooming** [comment]
This is a sync to FlyingBear from the original version.
https://github.com/miblooming/JZ-TS24-2/tree/master/other/JZ-TS40WIFI___4.0fb_sync

**Comment by Yandex-an** [comment]
Thanks you)
