### ISSUE TITLE
how to increase the transfer speed over Wi-Fi

### ISSUE THREAD

**Issue by dacentichka** [miblooming/JZ-TS24-2#43]
good day skadite how to increase the speed of transmission over wifi

**Comment by dacentichka** [comment]
![IMG_20201123_174457_699](https://user-images.githubusercontent.com/60215519/99975692-9fe65380-2db3-11eb-8283-b855d728c9ba.jpg)

**Comment by miblooming** [comment]
1. Use a faster SD card, recommend a card of class 10 or higher
2. Make the printer in a position with strong WIFI signal
3. Reduce the number of files stored on the SD card



 
---Original---

**Comment by dacentichka** [comment]
and what is the maximum speed can be?, please attach a photo, and if it is not difficult for you, tell us what interface Wi-Fi records files?

**Comment by miblooming** [comment]
about 200KB/s. The ability of the STM32 Chip is not that powerful to receive data from wifi.
Try this:
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/WifiHelper
Is same as that cura plugin.

**Comment by dacentichka** [comment]
thank you, this did not help, I will continue to use a third-party plugin for Kura, as it is more functional. have a nice day)
