### ISSUE TITLE
Filament Unload at End of Printing

### ISSUE THREAD

**Issue by PI-Beginner** [miblooming/JZ-TS24-2#8]
Switch button "Unload Filament" at the end of Print --> Like "Ending Sound"
Switch button should have linkage to  G-Code  (editable)

**Comment by miblooming** [comment]
Please upgrade to the newest version.
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)
![switch_button](https://user-images.githubusercontent.com/2108904/61650517-7c565900-ace6-11e9-8bd0-7c1615fea892.png)
![event_after_printing_task_finish](https://user-images.githubusercontent.com/2108904/61650534-84ae9400-ace6-11e9-99e2-e4214aa62d1f.png)
