### ISSUE TITLE
Buttons for Filament Load/Unload at Extruder Menu

### ISSUE THREAD

**Issue by PI-Beginner** [miblooming/JZ-TS24-2#9]
see example
- better design as mine
- for Extr 0 and 1 
- with feedback --> aktiv and done
- link to G-Code (editable)

![IMG_20190515_074027546](https://user-images.githubusercontent.com/50876608/58104666-6f819000-7be5-11e9-908a-950f3e02a4bf.jpg)

G-Code example for unload BMG-Extruder on Ender-3:
M109 S220.000
G92 E0 
G1 E10 F100
G92 E0 
G1 E-480 F2000 
G92 E0
M109 S0
M400

for load:

M109 S220.000
G92 E0 
G1 E400 F2000
G92 E0
G1 E100 F200
G92 E0
G1 E-10 F200
G92 E0
M400

**Comment by miblooming** [comment]
https://github.com/miblooming/JZ-TS24-2/tree/master/JZHelper_ui_editor/JZ-TS35WIFI___(3.5%264.0)/UIEditor_landscape
![filament_change (1)](https://user-images.githubusercontent.com/2108904/61651054-a9573b80-ace7-11e9-9d02-f14652bba9bd.png)
![filament_change (2)](https://user-images.githubusercontent.com/2108904/61651063-ab20ff00-ace7-11e9-90bd-969e723fc7bc.png)
